### ISSUE TITLE
[Epic] Search

### ISSUE THREAD

**Issue by Ferdi** [mitodl/lore#120]
This is a meta issue (epic) to document LORE search requirements and progress.  Please create sub-issues and submit PRs against them.
- [x] ~~#139~~ Set-up the search infrastructure. E.g. integration with django-haystack, installing the search engine (elasticsearch / solr)
- [x] ~~#142~~ Set up indexing to occur during import
- [x] ~~#144~~ Make the repository listing page powered by search 
- [x] Free text search on the contentxml field and the UI  
- [x] ~~#158~~ Facets for dynamic metadata (course, run, learningresource type)  
- [x] ~~#159~~ Facets for user-defined metadata (vocabulary based)
- [x] ~~#155~~ Update search index when taxonomy items are changed

**Comment by ShawnMilo** [comment]
What is meant by `Make the repository listing page powered by search`? It seems like this is the free-text search below it. Is this just having the "filter buttons" back on the left side for things like Item Type?

**Comment by pdpinch** [comment]
Removed assignment since this is an epic and individual issues may be assigned to different folks.

**Comment by Ferdi** [comment]
@ShawnMilo , does #144 answers your question ?

**Comment by ShawnMilo** [comment]
Yes, thanks.

**Comment by ShawnMilo** [comment]
Question about "Free text search on the contentxml field and the UI":

I believe the first part is being able to search what we're already indexing. That makes sense. What does "and the UI" mean? Just the form on the listing page for the search box?

**Comment by Ferdi** [comment]
Yes, by "UI" I meant simply the search box in the listing page

**Comment by ShawnMilo** [comment]
Thanks.

**Comment by ShawnMilo** [comment]
@Ferdi: Do you want to add #155 to your original post at the top, or should it be a separate issue?

**Comment by pdpinch** [comment]
all done.
