### ISSUE TITLE
As a curator, I need to associate static assets with learning resources

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#123]
- [x] import the static assets (PR #199)
- [x] add field to learning resource model for static assets (PR #199)
- [ ] parse learning resource XML for links to static assets
  - [x] #230 parse video blocks
  - [x] #231 parse problem and html blocks
  - [ ] parse jsinput blocks (later)
  - [ ] parse iframe blocks (later)
- [x] #254 add tab in detail view for viewing list of static assets (with links)
- [ ] ui for users to identify assets that were missed by the XML parser (later)
- [ ] deal with exported asset name collisions (later)

When a course is imported, we can make some assumptions about the relationship between learning resources and static assets based on links, but it would be very hard (if not impossible) for us to determine static dependencies with the static assets. I.e. the course author could have linked a javascript file that calls other javascript files. 

To deal with this, we need to provide the curator with a way to add static files that are missed.

**Comment by pdpinch** [comment]
This issue can be closed when new issues are opened for the following:
- [ ] parse jsinput blocks (later)
- [ ] parse iframe blocks (later)
- [ ] ui for users to identify assets that were missed by the XML parser (later)
- [ ] deal with exported asset name collisions (later)
