### ISSUE TITLE
[Epic] Rest APIs

### ISSUE THREAD

**Issue by Ferdi** [mitodl/lore#138]
This is a meta issue (epic) to document LORE API requirements and progress. Please create sub-issues and submit PRs against them.
- [x]  #100 Integration with Django rest framework , settings, defaults, authentication and authorization, root api (http://goo.gl/gx58ll)
- [x]  #118 Basic documentation, overall structure, settings, defaults
- [x]  #132 Taxonomy REST API
- [x]  #129 Members REST API
- [x]  #162 Learning resources API
- [x]  Repositories API

**Comment by pdpinch** [comment]
@noisecapella this is done, isn't it? 

We never got a store for the repositories API. If that isn't done, can you help me write a story for the remaining work?

**Comment by noisecapella** [comment]
We do have a repositories API at `/api/v1/repositories/`, currently unused though

**Comment by noisecapella** [comment]
Yes, all this is done
