### ISSUE TITLE
Import

### ISSUE THREAD

**Issue by Ferdi** [mitodl/lore#164]
- [x] ~~#21~~ / ~~#4~~ Basic Import   / Importer app
- [x] ~~#28~~ Asynchronous Course Import
- [ ] #111 As a curator, I'd like to know the state of my import 
- [ ] #112 As a curator, I'd like to be able to retry my uploads
- [ ] #113 Change upload to use S3 instead of directly to the app
- [ ] #123 As a curator, I need to associate static assets with learning resources
- [x] #109 / #145 make asynchronous upload work in Heroku
