### ISSUE TITLE
Export learning resources

### ISSUE THREAD

**Issue by Ferdi** [mitodl/lore#165]
- [x] #357 per-user shopping cart allows user to build sequence of learning resources
- [x] #358 user can "preview" list of learning resources before export
- [x] #387 Export builds gzip'ed file containing XML and static assets
- [x] user can empty shopping cart

For Future:
- [ ] make shopping cart persistent

![export](https://cloud.githubusercontent.com/assets/125561/8151669/d1b5e622-12df-11e5-86c8-d661fe4f9767.png)
