### ISSUE TITLE
Roles and permissions 

### ISSUE THREAD

**Issue by Ferdi** [mitodl/lore#26]
- [x] #129 Members REST API for managing users in repositories 
- [x] #160 Roles and permissions: Create a lore_admin role 
- [x] #132 Add authorizations to the taxonomy APIs

![screenshot 2015-05-18 11 00 25](https://cloud.githubusercontent.com/assets/125561/7683443/37b33d60-fd4d-11e4-9e76-f6edf4a7b652.png)

**Comment by pdpinch** [comment]
@Ferdi do we want to close this issue now that the initial feature is merged? Or do we want to turn this issue into an epic like the others?

**Comment by Ferdi** [comment]
epic is good. I'm sure we'll have more issues related to roles and permission. It be great to have a place to summarize and track progress.

**Comment by pwilkins** [comment]
As currently implemented, the `Admin` role can't have the permissions to create repositories, since the repository has to exist before the `Admin` role is created.  I created issue #149 to track this problem.
