### ISSUE TITLE
Preview

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#351]
Use the url_name of the learning resource with a jump_to_id edX request to open the correct view

If there is no url_name, we can live with the default results from edX
- [x] Add a configuration variable for the base URL for preview (staging for us)
- [x] add preview link to listing view
- [x] add preview link to learning resource panel
- [x] Construct the URL from base URL/org/course/jump_to_id/url name (or something like that)
     Similar to how analytics.odl.mit.edu links out
- [x] open a new window to make it easier for the user to navigate

**Comment by pdpinch** [comment]
Closed by #352 and #399
