### ISSUE TITLE
Edit vocabulary

### ISSUE THREAD

**Issue by Ferdi** [mitodl/lore#380]
Users may want to edit the vocabulary to , for example, change the types of learning resources that vocabulary applies to. 

See http://pureui.com/c/mit/lore/build004/
- [x] #506 Editing a term should make the term editable in place in the taxonomies panel
- [x] #507 deleting a term should remove it from all learning resources
- [x] #504 Editing a vocabulary should open the Vocabulary tab and populate the form with current values. 
- [x] #505 Deleting a vocabulary should remove all its terms from all learning resources, and delete the vocabulary as well. 
- [x]  Deleting is quite destructive. There needs to be a confirmation dialog

**Comment by noisecapella** [comment]
Are there any UI mockups available for this feature?

**Comment by pdpinch** [comment]
Yes, there are ui mockups. I updated the issue with more description.

**Comment by amir-qayyum-khan** [comment]
- On clicking edit vocabulary button, I will switch tab and open vocabulary in edit mode. Save button will be change into update. And will add cancel button along with update. On pressing cancel or  update I will clear form and switch back to listing tab. In case of update I will update vocabulary. (Will see if there is any need to change API)
- On clicking delete button I will show a confirmation dialog. On confirming I will first delete all terms in vocabulary (Need to see if there is any api or that who delete terms by given vocabulary slang).
  Then i will delete vocabulary and re-render list. 
- On clicking Edit term, I will add in place editing box. where user can edit and save that term. And there will be cancel button to exit edit mode. On save I will re-render list.
- On clicking delete term, I will show a confirmation dialog. On conforming I will remove that term  and re-render list.

@pdpinch can you guide me toward the new UI design for editing and delete.

**Comment by Ferdi** [comment]
Can we split this in  smaller issues 
- Edit vocabulary
- Delete vocabulary
- Edit term
- Delete term

**Comment by amir-qayyum-khan** [comment]
Yes we can. Do i need to create these issues on github or I just need to create 4 PRs for these tasks?

**Comment by Ferdi** [comment]
Issues for each would be great.

**Comment by amir-qayyum-khan** [comment]
@pdpinch this epic is complete. It is consist of all taxonomy task related to edit and delete.
