### ISSUE TITLE
New facet: Curation status

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#512]
Physics team would want a "default" facet  (like "Item type") that will have the following possible state/values :
- Ready-To-Use: Content is ready to drop in a course without editing, and has a complete set of metadata associated with it (topic, learning objectives, keywords).  
- Tagged: Minimally curated content. Incomplete metadata, or needs editing to be used in a course.  
- Course Information: Content that is tagged as course (and often course run) specific information, with no library purpose other than rerunning a course.
- Discarded: Material that is completely irrelevant and not intended for further use. By default, anything with this status should not be exported in a rerun export. E.g., temporary working chapters, discussion blocks. Can also include irrecoverably bad content.
- Hidden: Objects required for internal structure, but not intended to be searchable. E.g., verticals with one entry.
- (No tag): Default status. Essentially untouched material, uncurated , directly imported from a course.

Some of these values must be manually assigned by a user in the learning resource edit form (e.g.  "Ready-To-Use") but others can change state automatically.

**Comment by pdpinch** [comment]
@Ferdi what should we do for UI for this? I think you had suggested using a special (text) search term.

**Comment by Ferdi** [comment]
To add some more context , Physics team would want a "default" facet  (like "Item type") that will have the following possible state/values :

* Ready-To-Use: Content is ready to drop in a course without editing, and has a complete set of metadata associated with it (topic, learning objectives, keywords).

* Tagged: Minimally curated content. Incomplete metadata, or needs editing to be used in a course.

* Course Information: Content that is tagged as course (and often course run) specific information, with no library purpose other than rerunning a course.

* Discarded: Material that is completely irrelevant and not intended for further use. By default, anything with this status should not be exported in a rerun export. E.g., temporary working chapters, discussion blocks. Can also include irrecoverably bad content.

* Hidden: Objects required for internal structure, but not intended to be searchable. E.g., verticals with one entry.

* (No tag): Default status. Essentially untouched material, uncurated , directly imported from a course.

**Comment by pdpinch** [comment]
Break this into separate stories:
- [ ] #534 automatically add this vocabulary to every repo, with all terms created as normal. Regular vocabulary, added to all courses. Still editable. Need to be able to update our existing repos. But we won't update them going forward. 
  _3_
- [ ] #535 create the "-- not set --" search filter so it's possible to facet on items without a value. Scoped within a particular vocabulary. Would be nice to have a "no term" filter for each vocabularies. 
  _2_
- [ ] #575 discovery: investigate options for hiding "hidden" tags from search results
- [ ] #576 separate "curation status" from "hidden"
- [ ] discovery: investigate options for the automated "hidden" tag

**Comment by ShawnMilo** [comment]
It seems that, under the covers, we should treat "discarded" identically to "hidden." If we do not, we'll have to manipulate it further in the UI so that the export checkbox is disabled, and doing so may frustrate some users. Better not to show them. Any objections?

**Comment by ShawnMilo** [comment]
The best way to implement the "no term" filter is to actually add a term to every vocabulary, for example `--not set--`.

It is [evidently possible](https://github.com/django-haystack/django-haystack/issues/824) to pass a query through Haystack to only show those that are missing, but that would not show a count next to `--not set--`, so if that count was desired (and I assume it would be) then we'd have to query a count from Elasticsearch _and_ PostgreSQL to figure out how many were missing. There would also be other hacks required to make this "fake facet" act like an actual facet.

Also, doing this without adding a term surch as `--not set--` into Elasticsearch would require more subclassing or overrides to Haystack objects, so it would take longer and be more difficult.

The two possible complications I see are if a curator ever wanted to use `--not set--` (or whatever we decide upon) as an actual term label, and ensuring that the `--not set--` label is always last in the term list on the search page. I think the former is unlikely (and we can easily select any value for this), and the second should be easy.

**Comment by pdpinch** [comment]
Would you have to add some logic to remove `-- not set --` whenever another value is chosen?

I'm not sure that `-- not set --` needs to be the last facet. I'd be fine with it sorting as normal, as long as it always appears.

**Comment by ShawnMilo** [comment]
@pdpinch: Great catch on removing it when others are added; that's on my list. I think it's nice if it can appear at the bottom for consistency, and that's already been done without any difficulty. As a side-effect, it also orders the other options alphabetically, where before they were random.

**Comment by ShawnMilo** [comment]
I've run into an issue trying to do TDD here. Creating a `Repository` does not give the user who created it the proper permissions unless the repo is created using the restful API.

This is a problem because I have a signal on `post_save` which creates the "curation status" vocabulary for the repo when it is added. For this, I am following the convention in the taxonomy API, which is to accept `repo_slug` and call `learningresources.api.get_repo` with the slug and `user_id` to get the repo. Here, it fails due to a lack of permissions.

One possibility is to move the calls to `roles.api` functions (such as `assign_user_to_repo_group`) to `Repository.save()` or a signal. Since the user is known (thanks to `Repository.created_by`, there is no need to have `request.user` in scope at the time.

Thoughts, @giocalitri, @noisecapella?

**Comment by noisecapella** [comment]
It seems inconsistent if only `Repository.save` assigns permissions and not any of the other models' `save` methods, although it seems like a reasonable permission to assign. I could go either way here

**Comment by ShawnMilo** [comment]
When a vocabulary is created, the user can select which `LearningResourceType`s it applies to.

Does the curation status apply to _all_ types, or just a subset? @pdpinch

**Comment by ShawnMilo** [comment]
Note: The migration for backfilling the curator vocabulary to existing repositories and setting the "not set" default on all existing LearningResources implicitly causes a re-index of the entire database.

Just FYI, because the deployment on this one could be slow. It took under 90 seconds locally, but YMMV.

**Comment by pdpinch** [comment]
All types.

**Comment by pdpinch** [comment]
Thanks for the heads up.

Based on what I was told by devops yesterday, an index update may be slow but it's non-blocking.

**Comment by ShawnMilo** [comment]
In the case migrations running during deployment I think it would be
blocking. Running a management command on a running instance is slow but
non-blocking, which is what we were discussing yesterday.

**Comment by carsongee** [comment]
As long as the old code can run on the new migrations, we can migrate before deployment and avoid the issue. Can you maybe test that scenario before merging, or has it already merged?

**Comment by ShawnMilo** [comment]
It's far from merged. :o) It's still a WIP.

I don't think the old code will have any issues running with the new
migrations -- it's a data migration only.

**Comment by pwilkins** [comment]
The feature intent and implementation described in this issue has been reverted. It is replaced by a different approach described in #575 and #576
