### ISSUE TITLE
ability to facet on "not tagged"

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#591]
As a curator, I would like an easy way to find all the learning resources that have not had any term applied in given vocabulary. 
- [x] #616 **query** [ElasticSearch has a "missing" type filter](https://www.elastic.co/guide/en/elasticsearch/guide/current/_dealing_with_null_values.html#_missing_filter) that can be used to find all documents that are missing a particular field (when a field has no value, it simply doesn't exist in in the document).
- [ ] #676 **UI** Add a "not tagged" items to the list of terms in the facet. This term should be styled differently, but we haven't determined what that will be yet. 
- [x] #617 **behavior** Clicking the number should perform a query that returns a set of the learning resources with no value for that field. Otherwise, the query should behave the same as any other facet. The facet label will need to remain visible, unlike it does currently. 
- [x] **performance**  we should include some statsd instrumentation on this. There's some concern that it will entail an additional query besides the facet queries.

**Comment by giocalitri** [comment]
I tested this
https://github.com/django-haystack/django-haystack/issues/824
and it works:

```
In [1]: from search.forms import SearchForm
In [2]: form = SearchForm(repo_slug='small', sortby='nr_views')
In [3]: res = form.search()
In [4]: len(res) # toy course
Out[4]: 18

# 2 terms have the vocabulary "color" set; the vocabulary "color" has ID=3
In [5]: missing = res.filter(_missing_='3_exact')
In [6]: len(missing)
Out[6]: 16
```

What's missing is how we plug this feature of Haystack to the UI: need to do some more research and tests.

The main problem I see is how to fetch the number without making additional requests to the backend

**Comment by giocalitri** [comment]
Plug statsd
https://github.com/mitodl/lore/pull/494/files#diff-1b6759f04bef35c97141ab7bc4024a44R191

**Comment by giocalitri** [comment]
@Ferdi suggested to not put the missing number next to the Vocabulary label, but to create an additional entry in the list with term name "not tagged". this entry should eventually be styled differently.

cc @pdpinch

**Comment by pdpinch** [comment]
I updated the description to follow Giovanni's comment above, https://github.com/mitodl/lore/issues/591#issuecomment-139259659

**Comment by pdpinch** [comment]
@giocalitri did we ever do any statsd instrumentation on the "not tagged" term? What is your feeling about performance?

**Comment by giocalitri** [comment]
I put a decorator for the search API. I didn't look at the results.
