### ISSUE TITLE
Add elasticsearch-dsl querying.

### ISSUE THREAD

**Issue by ShawnMilo** [mitodl/lore#668]
Based on the research done in #516, add direct use of the `elasticsearch` and `elasticsearch_dsl` libraries.

These will temporarily run in parallel to the Haystack code, until the front-end and restful API are updated, then all the Haystack code can be completed.
- [x] Duplicate existing Haystack functionality with above libraries #669
- [x] Add converter to transform existing requests from what Haystack expects to what Elasticsearch-DSL uses, and a converter to transform the results of an Elasticsearch-DSL query to what the existing front-end/API expects. #680
- [ ] Update front-end (React) code to use the new functions
- [ ] Update the restful API to use the new functions

**Comment by ShawnMilo** [comment]
FYI @pdpinch. #669 is the part I'm working on now (first checkbox above).

**Comment by Ferdi** [comment]
> Update front-end (React) code to use the new functions 

I thought react only uses the REST api ?

**Comment by noisecapella** [comment]
He's referring to the change in output from the REST API which will require slight changes to the React code that consumes it.

**Comment by pdpinch** [comment]
@ShawnMilo I think the 3rd and 4th checkboxes are complete on this, and we can close this issue. Can you confirm?

**Comment by ShawnMilo** [comment]
@pdpinch Not really. The data being pulled by elasticsearch-dsl is being converted to what Haystack had been returning. The actual learning resources aren't really different, since they're essentially being returned as a list of dictionaries.

However, the aggregate data (vocabulary counts) are being converted to the Haystack format by the `convert_aggregate` function in `search/utils.py`.

It would be _nice_ to clean up, but I don't think it's really hurting anything to leave it as-is. @noisecapella or @giocalitri can comment on how much trouble it would be to clean up the react.js parts so we can scrap `convert_aggregate`.
